# ==============================================================================
# Project Pele: HTGR RVE Matrix 
# Coupled Steady-State Thermal-Mechanical Analysis
# ==============================================================================

[Mesh]
  # Load the SI-scaled Exodus mesh generated by Coreform Cubit
  [fmg]
    type = FileMeshGenerator
    file = '../meshes/htgr_rve_mesh.e'
  []
[]

[Variables]
  # Primary thermal variable solved via heat conduction
  [temperature]
    order = FIRST
    family = LAGRANGE
    initial_condition = 300
  []
[]

[GlobalParams]
  # Globally define displacement variables for the SolidMechanics physics block
  displacements = 'disp_x disp_y disp_z'
[]

[Physics]
  # Automatically generates the necessary Tensor Mechanics kernels
  [SolidMechanics]
    [QuasiStatic]
      [all]
        strain = SMALL
        add_variables = true
        eigenstrain_names = thermal_expansion
        generate_output = 'vonmises_stress hydrostatic_stress'
        temperature = temperature
      []
    []
  []
[]

[Kernels]
  # Heat equation terms: -k * Laplacian(T) = Q
  [heat_conduction]
    type = HeatConduction
    variable = temperature
  []
  
  # Note: The volumetric [heat_source] BodyForce was removed. 
  # Heat now enters the matrix exclusively through the fuel_wall boundary.
[]

[BCs]
  # Convective heat transfer cooling applied ONLY to the coolant channel
  [convective_cooling]
    type = ConvectiveHeatFluxBC
    variable = temperature
    boundary = 'coolant_wall'
    T_infinity = 600
    heat_transfer_coefficient = 2000
  []

  # Heat flux from the TRISO compact entering the graphite matrix
  [fuel_heat_flux]
    type = NeumannBC
    variable = temperature
    boundary = 'fuel_wall'
    value = 5e5  # Placeholder: W/m^2 (Positive value adds heat to the domain)
  []

  # --- Symmetry Kinematic Constraints ---
  # Applying roller boundaries to the minimum symmetry planes and 
  # bottom face perfectly prevents rigid body motion.
  
  [symm_x]
    type = DirichletBC
    variable = disp_x
    boundary = 'symm_x_min'
    value = 0
  []
  
  [symm_y]
    type = DirichletBC
    variable = disp_y
    boundary = 'symm_y_min'
    value = 0
  []
  
  [bottom_z]
    type = DirichletBC
    variable = disp_z
    boundary = 'bottom_face'
    value = 0
  []
[]

[Materials]
  # --- Thermal Properties (H-451 Nuclear Graphite) ---
  [graphite_conductivity]
    type = ParsedMaterial
    block = 'matrix_graphite'
    property_name = 'thermal_conductivity'
    coupled_variables = 'temperature'
    expression = '11000 / temperature' # Baseline fit for H-451
  []

  [graphite_heat_capacity]
    type = GenericConstantMaterial
    block = 'matrix_graphite'
    prop_names = 'specific_heat'
    prop_values = '750'
  []

  # --- Mechanical Properties (H-451 Nuclear Graphite) ---
  [elasticity_tensor]
    type = ComputeIsotropicElasticityTensor
    block = 'matrix_graphite'
    youngs_modulus = 9.8e9
    poissons_ratio = 0.13
  []
  
  [linear_stress]
    type = ComputeLinearElasticStress
    block = 'matrix_graphite'
  []

  [thermal_expansion]
    type = ComputeThermalExpansionEigenstrain
    block = 'matrix_graphite'
    temperature = temperature
    stress_free_temperature = 300
    thermal_expansion_coeff = 4.0e-6
    eigenstrain_name = thermal_expansion
  []
[]

[Executioner]
  type = Steady
  solve_type = 'PJFNK'
  petsc_options_iname = '-pc_type -pc_hypre_type'
  petsc_options_value = 'hypre boomeramg'
[]

[Postprocessors]
  [max_T]
    type = NodalExtremeValue
    variable = temperature
  []
  
  [max_vonmises]
    type = ElementExtremeValue
    variable = vonmises_stress
  []
[]

[Outputs]
  exodus = true
  csv = true
  print_linear_residuals = false
[]